import { supabase } from '../config/supabaseClient';
import { recentActivity, trucks } from './mockData';

// Helper to convert empty strings generated by form inputs to true nulls for Postgres
const sanitizeForPostgres = (data) => {
    const cleanData = { ...data };
    for (const key in cleanData) {
        if (cleanData[key] === "") {
            cleanData[key] = null;
        }
    }
    return cleanData;
};

export const fetchTrucks = async () => {
    console.log('🚛 fetchTrucks: Starting to fetch trucks from Supabase...');
    try {
        const { data: trucksData, error } = await supabase
            .from('trucks')
            .select('*')
            .order('truckNumber', { ascending: true });

        if (error) throw error;

        console.log('✅ fetchTrucks: Successfully fetched', trucksData.length, 'trucks');
        return trucksData;
    } catch (error) {
        console.error("❌ Error fetching trucks:", error.message);
        console.log('⚠️ Falling back to mock data.');
        return trucks;
    }
};

export const fetchTruckById = async (id) => {
    try {
        const { data, error } = await supabase
            .from('trucks')
            .select('*')
            .eq('id', id)
            .single();

        if (error) throw error;
        return data;
    } catch (error) {
        console.error("❌ Error fetching truck by id:", error.message);
        return null;
    }
};

export const addTruck = async (truckData) => {
    console.log('🚛 addTruck: Attempting to add truck to Supabase...', truckData);
    const sanitizedData = sanitizeForPostgres(truckData);

    try {
        const { data, error } = await supabase
            .from('trucks')
            .insert([sanitizedData])
            .select()
            .single();

        if (error) throw error;

        console.log('✅ addTruck: Successfully added truck with ID:', data.id);
        return data.id;
    } catch (error) {
        console.error("❌ Error adding truck:", error.message);
        return "mock-truck-id-" + Date.now();
    }
};

export const getOverdueTrucks = async () => {
    try {
        const today = new Date();
        today.setHours(0, 0, 0, 0);

        const { data, error } = await supabase
            .from('trucks')
            .select('*')
            .not('nextDueDate', 'is', null)
            .lt('nextDueDate', today.toISOString().split('T')[0]);

        if (error) throw error;
        return data;
    } catch (error) {
        console.error("Error fetching overdue trucks:", error.message);
        return [];
    }
};

export const getDueSoonTrucks = async () => {
    try {
        const today = new Date();
        today.setHours(0, 0, 0, 0);

        const nextWeek = new Date(today);
        nextWeek.setDate(today.getDate() + 7);

        const { data, error } = await supabase
            .from('trucks')
            .select('*')
            .not('nextDueDate', 'is', null)
            .gte('nextDueDate', today.toISOString().split('T')[0])
            .lte('nextDueDate', nextWeek.toISOString().split('T')[0]);

        if (error) throw error;
        return data;
    } catch (error) {
        console.error("Error fetching due soon trucks:", error.message);
        return [];
    }
};

export const getDashboardStats = async () => {
    try {
        const { count: total, error: totalError } = await supabase
            .from('trucks')
            .select('*', { count: 'exact', head: true });

        if (totalError) throw totalError;

        const now = new Date();
        const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().split('T')[0];
        const endOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 1).toISOString().split('T')[0];

        const { data: thisMonthAlignments, error: monthError } = await supabase
            .from('alignments')
            .select('truckId, truckNumber')
            .gte('alignmentDate', startOfMonth)
            .lt('alignmentDate', endOfMonth);

        if (monthError) throw monthError;

        const alignedTruckIds = new Set(
            thisMonthAlignments.map(doc => doc.truckId || doc.truckNumber)
        );
        const okCount = alignedTruckIds.size;

        const overdueTrucks = await getOverdueTrucks();
        const dueSoonTrucks = await getDueSoonTrucks();

        return {
            totalTrucks: total || 0,
            ok: okCount,
            dueSoon: dueSoonTrucks.length,
            overdue: overdueTrucks.length
        };
    } catch (error) {
        console.error("Error fetching stats:", error.message);
        return {
            totalTrucks: 0,
            ok: 0,
            dueSoon: 0,
            overdue: 0
        };
    }
};

export const getRecentActivity = async () => {
    try {
        const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();

        const { data, error } = await supabase
            .from('alignments')
            .select('*')
            .gte('created_at', thirtyDaysAgo)
            .order('created_at', { ascending: false })
            .limit(5);

        if (error) throw error;
        return data;
    } catch (error) {
        console.error("Error fetching activity:", error.message);
        return recentActivity; // Mock fallback
    }
};

export const fetchAlignments = async (truckId) => {
    try {
        const { data, error } = await supabase
            .from('alignments')
            .select('*')
            .eq('truckId', truckId)
            .order('alignmentDate', { ascending: false });

        if (error) throw error;
        return data;
    } catch (error) {
        console.error("Error fetching alignments:", error.message);
        return [];
    }
};

export const fetchAllAlignments = async () => {
    try {
        const { data, error } = await supabase
            .from('alignments')
            .select('*')
            .order('alignmentDate', { ascending: false });

        if (error) throw error;
        return data;
    } catch (error) {
        console.error("Error fetching all alignments:", error.message);
        return [];
    }
};

export const addAlignment = async (alignmentData) => {
    const sanitizedData = sanitizeForPostgres(alignmentData);
    try {
        const { data, error } = await supabase
            .from('alignments')
            .insert([sanitizedData])
            .select()
            .single();

        if (error) throw error;

        // Update truck
        if (sanitizedData.truckId) {
            await supabase
                .from('trucks')
                .update({
                    nextDueDate: sanitizedData.nextDueDate,
                    lastAlignmentDate: sanitizedData.alignmentDate,
                    status: 'OK'
                })
                .eq('id', sanitizedData.truckId);
        }

        return data.id;
    } catch (error) {
        console.error("Error adding alignment:", error.message);
        return "mock-alignment-id-" + Date.now();
    }
};

// --- BILLING SERVICES ---

export const getNextInvoiceNumber = async () => {
    try {
        const { count, error } = await supabase
            .from('bills')
            .select('*', { count: 'exact', head: true });

        if (error) throw error;

        const nextNum = (count || 0) + 1;
        return `INV-${String(nextNum).padStart(3, '0')}`;
    } catch (error) {
        console.error("Error fetching next invoice number:", error.message);

        // Offline fallback using localStorage
        const localLast = localStorage.getItem('lastInvoiceNo');
        if (localLast) {
            const numMatch = localLast.match(/\d+$/);
            if (numMatch) {
                const nextNum = parseInt(numMatch[0], 10) + 1;
                return `INV-${String(nextNum).padStart(3, '0')}`;
            }
        }
        return 'INV-001';
    }
};

export const saveBill = async (billData) => {
    const sanitizedData = sanitizeForPostgres(billData);
    
    // Always store latest invoice number locally so sequences continue even if offline
    if (sanitizedData.invoiceNo) {
        localStorage.setItem('lastInvoiceNo', sanitizedData.invoiceNo);
    }

    try {
        const { data, error } = await supabase
            .from('bills')
            .insert([sanitizedData])
            .select()
            .single();

        if (error) throw error;
        return data.id;
    } catch (error) {
        console.error("Error saving bill:", error.message);
        throw error;
    }
};

export const fetchAllBills = async () => {
    try {
        const { data, error } = await supabase
            .from('bills')
            .select('*')
            .order('created_at', { ascending: false });

        if (error) throw error;
        return data;
    } catch (error) {
        console.error("Error fetching all bills:", error.message);
        return [];
    }
};

export const getPendingBills = async () => {
    try {
        const { data, error } = await supabase
            .from('bills')
            .select('*')
            .eq('paymentStatus', 'Pending')
            .order('created_at', { ascending: false });

        if (error) throw error;
        return data;
    } catch (error) {
        console.error("Error fetching pending bills:", error.message);
        return [];
    }
};

export const markBillPaid = async (billId) => {
    try {
        const { error } = await supabase
            .from('bills')
            .update({
                paymentStatus: 'Paid',
                paidAt: new Date().toISOString()
            })
            .eq('id', billId);

        if (error) throw error;
        return true;
    } catch (error) {
        console.error("Error marking bill as paid:", error.message);
        throw error;
    }
};

export const addPartialPayment = async (billId, currentAdvance, newPaymentAmount, totalAmount) => {
    try {
        const newAdvance = (currentAdvance || 0) + Number(newPaymentAmount);
        const newBalance = totalAmount - newAdvance;

        const updateData = {
            advancePaid: newAdvance,
            balanceDue: newBalance,
            lastPaymentAt: new Date().toISOString()
        };

        if (newBalance <= 0) {
            updateData.paymentStatus = 'Paid';
            updateData.paidAt = new Date().toISOString();
        }

        const { error } = await supabase
            .from('bills')
            .update(updateData)
            .eq('id', billId);

        if (error) throw error;
        return newBalance <= 0 ? 'Paid' : 'Pending';
    } catch (error) {
        console.error("Error adding partial payment:", error.message);
        throw error;
    }
};
